name: SpecialBlock
author: Primus
api: 1.0.0
version: 1.3.2
main: Primus\Main
description: ""

commands:
 sb:
  usage: "/sb <get|set|list> <args> [args]"
  permission: sb.cmd
  default: OP
  description: "SpecialBlock main command"
