---
# General
interval: 10
# Damage Block
broadcast-on-chat: false
damage: 2
damage-block-name: Obsidian
damage-block: 49
death-message: '§l{PLAYER} 站在 §4{BLOCK} 而死亡\n§7翻譯：PocketMine-MP 伺服插件資源網 (http://PocketMinePlugins.reh.tw)'
# Effect
effect-block: 246
effect-id: 1
effect-amplifier: 2
effect-visibility: false
effect-duration: 1800
send-message-on-recieve: false
send-popup-on-recieve: false
effect-message: '§l§2<< §a獲得效果 §2>>'
effect-popup: '§l§2<< §a獲得效果 §2>>'
# Healing Block
healing-block: 121
healing-message: '§l§2<< §a治療 §2>>'
hp-gain: 2
...
