name: FineJoinEffects
main: Asidert\FineJoinEffects
version: 0.5
api: 1.0.0
author: Asidert
website: http://www.youtube.com/MrAsidert

permissions:
    finejoineffects:
        default: op
        description: "允許接收所有效果"
        children:
            finejoineffects.player:
                default: true
                description: "允許接收玩家效果"
            finejoineffects.vip:
                default: op
                description: "允許接收 VIP 效果"
