name: FineJoinEffects
main: Asidert\FineJoinEffects
version: 0.5
api: 1.0.0
author: Asidert
website: http://www.youtube.com/MrAsidert

permissions:
    finejoineffects:
        default: op
        description: "Allow to receive ALL effects"
        children:
            finejoineffects.player:
                default: true
                description: "Allow to receive player effects"
            finejoineffects.vip:
                default: op
                description: "Allow to receive VIP effects"